#index:
#    path: /
#    controller: App\Controller\DefaultController::index
register:
    path: /register
    controller: App\Controller\AuthenticationController::register
    methods: POST

api:
    path: /api
    controller: App\Controller\AuthenticationController::api

login_check:
    path:     /login_check
    methods:  [POST]


